config/routes.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Rails.application.routes.draw do


  resources :teachers do
    get 'delete'
    match 'import', :via => [:get, :post], :as => 'import'
    get 'download'
    get 'import_from_app'
  end
  resources :departments do
    get 'delete'
  end
  resources :forms do
    get 'delete'
  end
  resources :courses do
    get 'delete'
    match 'reset', :via => [:get, :post], :as => 'reset'
    match 'import', :via => [:get, :post], :as => 'import'
    get 'download'

  end
  resources :activities do
    get 'delete'
    get 'editS'
    get 'deleteS'
    get 'destroyS'
    get 'newS'
    match 'updateS', :via => [:patch, :post]
    get 'deleteall'
  end

  resources :cohorts do
    get 'delete'
    match 'import', :via => [:get, :post], :as => 'import'
    get 'import_from_app'
    get 'download'
  end
  resources :evaluation_sessions do
    get 'delete'
    match 'activate', :via => [:get, :post], :as => 'activate_session'
    match 'finalize', :via => [:get, :post], :as => 'finalize_session'
    match 'generate', :via => [:get, :post], :as => 'generate'
    get 'get_tokens'
  end

  get 'get_comments', :to => 'evaluation_sessions#get_comments'
  get 'get_comments_p', :to => 'prof#get_comments'
  match 'view_evaluation', :via => [:get, :post], :to => 'evaluation_sessions#view_evaluation'
  get 'descarca', :to => 'evaluation_sessions#descarca', :format => 'pdf'
  get 'download_evaluation', :to => 'evaluation_sessions#download_evaluation', :format => 'pdf'
  get 'download_evaluation_p', :to => 'prof#download_evaluation', :format => 'pdf'

  get 'evaluate' => 'evaluation#index'
  match 'evaluate_activity', :via => [:post, :get], :to => 'evaluation#evaluate_activity'
  match 'view_evaluation', :via => [:post, :get], :to => 'evaluation#view_evaluation'
  match 'view_eval_p', :via => [:post, :get], :to => 'prof#view_evaluation'

  match 'course_list', :via => [:post, :get], :to => 'courses#course_list'
  match 'cohort_list', :via => [:post, :get], :to => 'cohorts#cohort_list'
  match 'activities_neterminal_list', :via => [:post, :get], :to => 'evaluation_sessions#activities_neterminal_list'
  match 'activities_terminal_list', :via => [:post, :get], :to => 'evaluation_sessions#activities_terminal_list'

  get 'home/index'

  match 'set_visibility' , :via => [:post, :get], :to => 'evaluation_sessions#set_visibility'


  post 'create_active_user' => 'home#create'

  get 'view_statistics' => 'statistics#index'
  get 'download_all', :to => 'statistics#download_all'
  match 'download_all_pdf/:id', :to => 'statistics#download_all_pdf', via: :get, as: 'download_all_pdf'
  get 'download_by_cohorts', :to => 'statistics#download_by_cohorts'

  get 'course_statistics/:course_id' => 'statistics#course_statistics'
  get 'teacher_statistics/:teacher_id' => 'statistics#teacher_statistics'

  get 'evaluation_form/:activity_id' => 'evaluation#eval_form'

  get 'form_archive' =>'form#list_all'



  get 'control_panel' => 'control_panel#index'
  get 'control_panel/:tab' => 'control_panel#index'


  #get 'admin' => 'admin#index'

  get 'admin' => 'evaluation_sessions#current_session'

  get 'prof/index'

  get 'new_session' => 'evaluation_sessions#new1'
  get 'evaluation_sessions' => 'evaluation_sessions#index'

  get 'delete_all_activities_for_exam' => 'activities#delete_all_activities_for_exam'

  root 'home#index'

  match '/token_sign_out', to: 'home#abort_token_session', as: 'token_sign_out', via: [:get, :post]

  # omniauth
  match '/auth/:provider/callback', :via => [:get, :post], :to => 'user_sessions#create'
  match '/auth/failure', :via => [:get, :post], :to => 'user_sessions#failure'

  # Custom logout
  # match '/logout', :via => [:get, :post], :to => 'user_sessions#destroy'
  get 'alogin', to: 'user_sessions#new', as: 'login'
  get 'logout', to: 'user_sessions#destroy', as: 'logout'
  post 'alogin', to: 'user_sessions#create'

  #match 'test', :via => [:get], :to => 'cohorts#getAllCohorts'

end

app/models/evaluation_session.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

class EvaluationSession < ActiveRecord::Base
  belongs_to :form
  belongs_to :formS, :class_name => 'Form'
  belongs_to :formL, :class_name => 'Form'
  belongs_to :formP, :class_name => 'Form'
  has_many :eval_session_activities, dependent: :destroy
  has_many :evaluation_session_cohorts, :dependent => :destroy
  has_many :incognito_users, dependent: :destroy


  attr_accessor :from_upload
  attr_accessor :form1
  attr_accessor :form2
  attr_accessor :from_uploadL
  attr_accessor :formL1
  attr_accessor :formL2
  attr_accessor :from_uploadS
  attr_accessor :formS1
  attr_accessor :formS2
  attr_accessor :from_uploadP
  attr_accessor :formP1
  attr_accessor :formP2
  # Getter
  def session_status
    if self.end_date < Date.today
      if self.status != 'Finalizata'
        self.update(status: 'Finalizata')
      end
      'Finalizata'
    else
      self.status
    end
  end
  def sort_val
    return 2 if self.session_status == 'Activa'
    return 1 if self.session_status == 'Planificata'
    return 0 if self.session_status == 'Finalizata'
  end

  def identifier
    "#{year} - #{year+1} semestru #{semester} #{start_date.strftime('%d/%m')} - #{end_date.strftime('%d/%m')} "
  end

end

app/helpers/evaluation_sessions_helper.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

module EvaluationSessionsHelper
  include AdminHelper

  def getStats
    if @active_session.nil?
      id11 = EvaluationSession.where(status: 'Finalizata', terminal: true)
      if id11.last.nil?
        id1 = 0
      else
        id1 = id11.last.id
      end
    else
      id1 = @active_session.id
    end
    if @active_session_neterminal.nil?
      id22 = EvaluationSession.where(status: 'Finalizata', terminal: false)
      if id22.last.nil?
        id2 = 0
      else
        id2 = id22.last.id
      end
    else
      id2 = @active_session_neterminal.id
    end
    query = "SELECT count( distinct incognito_token), evaluation_session_cohorts.name
      FROM
        public.completed_evaluations,
        public.eval_session_activities,
        public.evaluation_sessions,
        public.evaluation_session_cohorts
      WHERE
        completed_evaluations.eval_session_activity_id = eval_session_activities.id AND
        eval_session_activities.evaluation_session_id = evaluation_sessions.id AND
        evaluation_session_cohorts.id = eval_session_activities.evaluation_session_cohort_id AND
        (evaluation_sessions.id = #{id1} or evaluation_sessions.id = #{id2} )
      group by evaluation_session_cohorts.name;"

    @results = ActiveRecord::Base.connection.execute(query).values

  end

  def updateData
    @terminal_tokens = IncognitoUser.where(evaluation_session: @active_session)

    @neterminal_tokens = IncognitoUser.where(evaluation_session: @active_session_neterminal)

    @departments_select = Department.all
    if @active_session.nil?
      @nrOfStudents = 0
    else
      @nrOfStudents = CompletedEvaluation.joins(:eval_session_activity).where(eval_session_activities: {evaluation_session_id: @active_session.id}).distinct.count(:incognito_token)
    end

    if @active_session_neterminal.nil?
      @nrOfStudentsNeterminal = 0
    else
      @nrOfStudentsNeterminal = CompletedEvaluation.joins(:eval_session_activity).where(eval_session_activities: {evaluation_session_id: @active_session_neterminal.id}).distinct.count(:incognito_token)
    end

  end


  def validate_request(id)
    parameters = evaluation_session_params

    if id.to_i > 0
      @evaluation_session = EvaluationSession.find(id)
    else
      @evaluation_session = EvaluationSession.new
      @evaluation_session.year = if Date.today.month > 8 then
                                   Date.today.year
                                 else
                                   Date.today.year - 1
                                 end
      @evaluation_session.semester = parameters['semester']
      @evaluation_session.status = 'Planificata'
    end
    if id.to_i > 0 and @evaluation_session.status == 'Activa'

    else

      # chestionar curs
      if parameters['from_upload'] == '1'
        if parameters['form1'].nil?
          @evaluation_session.errors[:base] << 'Va rugam specificati un formular pentru curs'

        else
          begin
            @chestionar = xml_file_to_json_string parameters['form1']
          ensure
            @evaluation_session.errors[:base] << 'Fisierul furnizat nu respecta formatul' unless @chestionar
          end
        end

      else
        if parameters['form2'].nil? or parameters['form2'].empty?
          @evaluation_session.errors[:base] << 'Va rugam specificati un formular pentru curs'
        else
          if id == 0 or (id > 0 and @evaluation_session.form_id != parameters['form2'])
            copied = Form.find(parameters['form2'])
            @evaluation_session.form_id = copied.id
            # @chestionar = copied.content
            # @chestionar_title = copied.title + '-' + Date.today.to_time.to_i.to_s
          end
        end
      end

      #chestionar seminar
      if parameters['from_uploadS'] == '1'
        if parameters['formS1'].nil?
          @evaluation_session.errors[:base] << 'Va rugam specificati un formular pentru seminar'

        else
          begin
            @chestionar_S = xml_file_to_json_string parameters['formS1']
          ensure
            @evaluation_session.errors[:base] << 'Fisierul furnizat nu respecta formatul' unless @chestionar_S
          end
        end

      else
        if parameters['formS2'].nil? or parameters['formS2'].empty?
          @evaluation_session.errors[:base] << 'Va rugam specificati un formular pentru seminar'
        else
          if id == 0 or (id > 0 and @evaluation_session.formS_id != parameters['formS2'])
            copied = Form.find(parameters['formS2'])
            @evaluation_session.formS_id = copied.id
            # @chestionar_S = copied.content
            #@chestionar_S_title = copied.title + '-' + Date.today.to_time.to_i.to_s
          end
        end
      end
      #chestionar lab
      if parameters['from_uploadL'] == '1'
        if parameters['formL1'].nil?
          @evaluation_session.errors[:base] << 'Va rugam specificati un formular pentru laborator'

        else
          begin
            @chestionar_L = xml_file_to_json_string parameters['formL1']
          ensure
            @evaluation_session.errors[:base] << 'Fisierul furnizat nu respecta formatul' unless @chestionar_L
          end
        end

      else
        if parameters['formL2'].nil? or parameters['formL2'].empty?
          @evaluation_session.errors[:base] << 'Va rugam specificati un formular pentru laborator'
        else
          if id == 0 or (id > 0 and @evaluation_session.formL_id != parameters['formL2'])
            copied = Form.find(parameters['formL2'])
            @evaluation_session.formL_id = copied.id
            #@chestionar_L = copied.content
            #@chestionar_L_title = copied.title + '-' + Date.today.to_time.to_i.to_s
          end
        end
      end
      #chestionar Proiect
      if parameters['from_uploadP'] == '1'
        if parameters['formP1'].nil?
          @evaluation_session.errors[:base] << 'Va rugam specificati un formular pentru proiect'

        else
          begin
            @chestionar_P = xml_file_to_json_string parameters['formP1']
          ensure
            @evaluation_session.errors[:base] << 'Fisierul furnizat nu respecta formatul' unless @chestionar_P
          end
        end

      else
        if parameters['formP2'].nil? or parameters['formP2'].empty?
          @evaluation_session.errors[:base] << 'Va rugam specificati un formular pentru proiect'
        else
          if id == 0 or (id > 0 and @evaluation_session.formP_id != parameters['formP2'])
            copied = Form.find(parameters['formP2'])
            @evaluation_session.formP_id = copied.id
            #@chestionar_L = copied.content
            #@chestionar_L_title = copied.title + '-' + Date.today.to_time.to_i.to_s
          end
        end
      end
    end
    if parameters['start_date'].nil?
      @evaluation_session.errors[:base] << 'Va rugam selectati data de incepere pentru anii neterminali'
    else
      @evaluation_session.start_date = parse_date parameters['start_date']
      @evaluation_session.errors[:base] << 'Data incepere ani neterminali este gresit formatata' unless @evaluation_session.start_date
    end

    if parameters['end_date'].nil?
      @evaluation_session.errors[:base] << 'Va rugam selectati data de final pentru anii neterminali'
    else
      @evaluation_session.end_date = parse_date parameters['end_date']
      @evaluation_session.errors[:base] << 'Data final ani neterminali este gresit formatata' unless @evaluation_session.end_date
    end
    if parameters['terminal'] == '1'
      @evaluation_session.terminal = true
    else
      @evaluation_session.terminal = false
    end

  end

  def parse_date(data)
    Date.strptime data, '%d-%m-%Y'
  rescue
    nil
  end


  def getAllEvaluationSessions(terminal)
    all = EvaluationSession.where(terminal: terminal)

    return all.sort_by {|session| [session.sort_val, session.id]}.reverse
  end


  def add_evaluation_session_activities (session)
    copied_ids = []
    year = if Date.today.month > 8 then
             Date.today.year
           else
             Date.today.year - 1
           end
    Cohort.where(is_terminal: session.terminal).each do |cohort|
      eval_cohort = EvaluationSessionCohort.new name: cohort.name, is_terminal: cohort.is_terminal, students_number: cohort.students_number, optionals_number: cohort.optionals_number, department: cohort.department, evaluation_session: session
      eval_cohort.save
      copied_ids[cohort.id] = eval_cohort.id
      Activity.where(cohort: cohort, semester: session.semester).each do |activity|
        eval_activity = EvalSessionActivity.new course: activity.course, is_optional: activity.is_optional, teacher: activity.teacher, year: year, semester: activity.semester, activity_type: activity.activity_type, evaluation_session: session, evaluation_session_cohort: eval_cohort
        eval_activity.save
      end
    end


  end


  # Generates a random string from a set of easily readable characters
  def generate_activation_code(size = 16)
    charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z a b c d e f g h j k  m n p q r s t u v w x y z = + / }
    (0...size).map {charset.to_a[rand(charset.size)]}.join
  end

app/views/evaluation_sessions/_activities_neterminal.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<% @activities_neterminal.each do |key, activities| %>
    <tr>
      <td>
        <%= Course.find_by_id(key[0]).title %>
      </td>
      <td>
        <% teacher = Teacher.find_by_id(key[1]) %>
        <%= teacher.last_name %> <%= teacher.first_name %>
      </td>
      <td><%= key[2] %></td>
      <td><%= link_to 'Vezi Evaluare', view_evaluation_path(:courseId => key[0], :teacherId => key[1], :type => key[2], :active_session => @active_session_neterminal), remote: true, class: 'btn btn-info' %></td>
      <td><%= link_to 'Descarca Comentarii', get_comments_path(:courseId => key[0], :teacherId => key[1], :type => key[2], :active_session => @active_session_neterminal), class: 'btn btn-info' ,  download:true%></td>
    </tr>
<% end %>

app/views/evaluation_sessions/_index.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<% @evaluation_sessions.each do |evaluation_session| %>
    <tr style="vertical-align: middle;">
      <td class="col-md-1">#<%= evaluation_session.id %></td>
      <td class="col-md-2"><%= evaluation_session.start_date.strftime('%d/%m/%y') %>
        - <%= evaluation_session.end_date.strftime('%d/%m/%y') %></td>

      <!-- <td class="col-md-2"><%= evaluation_session.form.title %></td>-->
      <td class="col-md-1"><%= evaluation_session.semester %>
      </td>
      <td class="col-md-1"><%= evaluation_session.year %>
        -<%= evaluation_session.year + 1 %></td>
      <td class="col-md-1"><%= evaluation_session.session_status %></td>
      <td class="col-md-1">

        <%= evaluation_session.visibility == true ? 'Da' : 'Nu' %>

      </td>
      <td class="col-md-1">
       <%= link_to 'Schimba vizibilitatea!', {:controller => "evaluation_sessions", :action => "set_visibility", :evaluation_id => evaluation_session.id }, method: :post, remote: true, class: 'btn btn-info' %>
      </td>
      <td class="col-md-1">
        <% if evaluation_session.session_status != 'Finalizata' && @active_session.nil? %>
            <%= link_to 'Activeaza!', evaluation_session_activate_session_path(evaluation_session.id), method: :get, remote: true, class: 'btn btn-info' %>
        <% end %>
        <% if !@active_session.nil? and @active_session.id == evaluation_session.id %>
            <%= link_to 'Finalizeaza!', evaluation_session_finalize_session_path(evaluation_session.id), method: :get, remote: true, class: 'btn btn-primary' %>
        <% end %>
      </td>

      <td class="col-md-3">
        <% if evaluation_session.session_status == 'Finalizata' %>
            <%= link_to '', edit_evaluation_session_path(evaluation_session.id), remote: true, class: 'btn glyphicon glyphicon-edit disabled' %>
        <% else %>
            <%= link_to '', edit_evaluation_session_path(evaluation_session.id), remote: true, class: 'btn glyphicon glyphicon-edit' %>
        <% end %>

        <%= link_to '', evaluation_session_delete_path(evaluation_session.id), remote: true, class: 'btn glyphicon glyphicon-trash' %>
        <%#= link_to '', evaluation_session_visibility_path(evaluation_session.id), remote: true, class: 'btn glyphicon glyphicon-ok' %>

        <%= link_to '', download_all_pdf_path(evaluation_session.id),download:true , class: 'btn glyphicon glyphicon-download' ,  data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> "}%>
      </td>

    </tr>
<% end %>

app/views/evaluation_sessions/_show_neterminal.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<% if @active_session_neterminal.nil? %>

    <h1>Nicio sesiune activa</h1>
<% else %>

    <br/>
    <div class="alert alert-info">
      Pana acum au evaluat <%= @nrOfStudentsNeterminal %> studenti din <%= @neterminal_tokens.length %>
    </div>
    <div class="well">
      <div class="pull-right">
        <%= link_to evaluation_session_generate_path(@active_session_neterminal.id), remote: true, class: 'btn btn-primary token-btn btn-no-padding' do %>
        <span class="btn-label">
    		<span class="fa fa-refresh"></span>
        </span>Genereaza Token-uri
        <% end %>
        <% if @neterminal_tokens and @neterminal_tokens.any? %>

            <%= link_to evaluation_session_get_tokens_path(@active_session_neterminal.id), class: 'btn btn-primary token-btn btn-no-padding',  download:true  do %>
        <span class="btn-label">
			<span class="fa fa-download"></span>
        </span>
                Descarca Token-uri
            <% end %>

        <% end %>


      </div>

      <div class="clearfix">
        <h4>
          Perioada de evaluare:
          <b> <%= @active_session_neterminal.start_date.strftime('%d/%m/%y') %>
            - <%= @active_session_neterminal.end_date.strftime('%d/%m/%y') %></b>
          <span style="margin-left: 10px;">    <b> Mai
         sunt <%= (@active_session_neterminal.end_date - @active_session_neterminal.start_date).to_i %>
            zile! </b></span>
        </h4>

        <div class="col-md-3 pull-right" style="padding-right: 0px;">

          <%= form_tag activities_neterminal_list_path, remote: true, class: "form-horizontal form", style: "display:inline;" do %>
              <%= select_tag :department, options_from_collection_for_select(@departments_select, 'id', 'name', '0'), include_blank: 'Toate', class: 'form-control ', :onChange => 'your_onchange_handler()' %>
          <% end %>
        </div>

        <h4>
          An universitar: <b> <%= @active_session_neterminal.year %> - <%= @active_session_neterminal.year + 1 %>,</b>
          <span style="margin-left: 10px;">  Semestrul: <b> <%= @active_session_neterminal.semester %></b></span>

        </h4>


        <% if !@active_session_neterminal.form.nil? %>
            <h4>
              Chestionar Curs:
              <b><%= link_to @active_session_neterminal.form.title, @active_session_neterminal.form, remote: true %></b>
            </h4>
        <% end %>
        <% if !@active_session_neterminal.formS.nil? %>
            <h4>
              Chestionar Seminar:
              <b><%= link_to @active_session_neterminal.formS.title, @active_session_neterminal.formS, remote: true %></b>
            </h4>
        <% end %>
        <% if !@active_session_neterminal.formL.nil? %>
            <h4>
              Chestionar Laborator:
              <b><%= link_to @active_session_neterminal.formL.title, @active_session_neterminal.formL, remote: true %></b>
            </h4>
        <% end %>
        <% if !@active_session_neterminal.formP.nil? %>
            <h4>
              Chestionar Proiect:
              <b><%= link_to @active_session_neterminal.formP.title, @active_session_neterminal.formP, remote: true %></b>
            </h4>
        <% end %>
      </div>
    </div>

    <div class="table-responsive">
      <table  id='active2' class="table table-striped table-hover"cellspacing="0" width="100%">
        <thead>
        <tr>
          <th>Materie</th>
          <th>Profesor</th>
          <th>Tip Activitate</th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody class="activities_neterminal">
        <%= render 'activities_neterminal' %>
        </tbody>
      </table>
    </div>
    <br>

    <script type="application/javascript">

        your_onchange_handler = function () {
            $(".form").submit();

        }
        $(document).ready(function() {

            $('#active2').DataTable();
        } );
    </script>
<% end %>