config/routes.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Rails.application.routes.draw do


  resources :teachers do
    get 'delete'
    match 'import', :via => [:get, :post], :as => 'import'
    get 'download'
    get 'import_from_app'
  end
  resources :departments do
    get 'delete'
  end
  resources :forms do
    get 'delete'
  end
  resources :courses do
    get 'delete'
    match 'reset', :via => [:get, :post], :as => 'reset'
    match 'import', :via => [:get, :post], :as => 'import'
    get 'download'

  end
  resources :activities do
    get 'delete'
    get 'editS'
    get 'deleteS'
    get 'destroyS'
    get 'newS'
    match 'updateS', :via => [:patch, :post]
    get 'deleteall'
  end

  resources :cohorts do
    get 'delete'
    match 'import', :via => [:get, :post], :as => 'import'
    get 'import_from_app'
    get 'download'
  end
  resources :evaluation_sessions do
    get 'delete'
    match 'activate', :via => [:get, :post], :as => 'activate_session'
    match 'finalize', :via => [:get, :post], :as => 'finalize_session'
    match 'generate', :via => [:get, :post], :as => 'generate'
    get 'get_tokens'
  end

  get 'get_comments', :to => 'evaluation_sessions#get_comments'
  get 'get_comments_p', :to => 'prof#get_comments'
  match 'view_evaluation', :via => [:get, :post], :to => 'evaluation_sessions#view_evaluation'
  get 'descarca', :to => 'evaluation_sessions#descarca', :format => 'pdf'
  get 'download_evaluation', :to => 'evaluation_sessions#download_evaluation', :format => 'pdf'
  get 'download_evaluation_p', :to => 'prof#download_evaluation', :format => 'pdf'

  get 'evaluate' => 'evaluation#index'
  match 'evaluate_activity', :via => [:post, :get], :to => 'evaluation#evaluate_activity'
  match 'view_evaluation', :via => [:post, :get], :to => 'evaluation#view_evaluation'
  match 'view_eval_p', :via => [:post, :get], :to => 'prof#view_evaluation'

  match 'course_list', :via => [:post, :get], :to => 'courses#course_list'
  match 'cohort_list', :via => [:post, :get], :to => 'cohorts#cohort_list'
  match 'activities_neterminal_list', :via => [:post, :get], :to => 'evaluation_sessions#activities_neterminal_list'
  match 'activities_terminal_list', :via => [:post, :get], :to => 'evaluation_sessions#activities_terminal_list'

  get 'home/index'

  match 'set_visibility' , :via => [:post, :get], :to => 'evaluation_sessions#set_visibility'


  post 'create_active_user' => 'home#create'

  get 'view_statistics' => 'statistics#index'
  get 'download_all', :to => 'statistics#download_all'
  match 'download_all_pdf/:id', :to => 'statistics#download_all_pdf', via: :get, as: 'download_all_pdf'
  get 'download_by_cohorts', :to => 'statistics#download_by_cohorts'

  get 'course_statistics/:course_id' => 'statistics#course_statistics'
  get 'teacher_statistics/:teacher_id' => 'statistics#teacher_statistics'

  get 'evaluation_form/:activity_id' => 'evaluation#eval_form'

  get 'form_archive' =>'form#list_all'



  get 'control_panel' => 'control_panel#index'
  get 'control_panel/:tab' => 'control_panel#index'


  #get 'admin' => 'admin#index'

  get 'admin' => 'evaluation_sessions#current_session'

  get 'prof/index'

  get 'new_session' => 'evaluation_sessions#new1'
  get 'evaluation_sessions' => 'evaluation_sessions#index'

  get 'delete_all_activities_for_exam' => 'activities#delete_all_activities_for_exam'

  root 'home#index'

  match '/token_sign_out', to: 'home#abort_token_session', as: 'token_sign_out', via: [:get, :post]

  # omniauth
  match '/auth/:provider/callback', :via => [:get, :post], :to => 'user_sessions#create'
  match '/auth/failure', :via => [:get, :post], :to => 'user_sessions#failure'

  # Custom logout
  # match '/logout', :via => [:get, :post], :to => 'user_sessions#destroy'
  get 'alogin', to: 'user_sessions#new', as: 'login'
  get 'logout', to: 'user_sessions#destroy', as: 'logout'
  post 'alogin', to: 'user_sessions#create'

  #match 'test', :via => [:get], :to => 'cohorts#getAllCohorts'

end

app/controllers/statistics_controller.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

class StatisticsController < AdminController
  include StatisticsHelper
  require 'csv'


  def index
    @current_tab = 'statistici'
    @all_sessions = EvaluationSession.where(status: "Finalizata")
    @courses = Course.all
    @teachers = Teacher.order(:last_name)
  end

  def course_statistics
    @current_tab = 'statistici'

    @course = Course.find_by_id(params['course_id'])

    ids = EvalSessionActivity.where(course_id: params['course_id']).pluck(:evaluation_session_id)
    @evaluation_sessions = EvaluationSession.order(:start_date).where(id: ids).reverse_order

  end

  def teacher_statistics
    @current_tab = 'statistici'

    @teacher = Teacher.find_by_id(params['teacher_id'])

    ids = EvalSessionActivity.where(teacher_id: params['teacher_id']).pluck(:evaluation_session_id)
    @evaluation_sessions = EvaluationSession.order(:start_date).where(id: ids).reverse_order

  end

  def download_by_cohorts
    # ids=[16,17,20,21,26,27,30,31]

    #ids = [36,38,39,42,35,37,40,41]

    # ids = [43,44,45,46,47,48,49,50]
    ids = [54, 57, 59, 55, 56, 58]

    #ids = EvaluationSession.all.pluck(:id)
    downloadable = []
    downloadable << 'Id Sesiune, Grupa, Nr Studenti'
    ids.each do |id|
      sql = "SELECT count( distinct incognito_token), evaluation_session_cohorts.name
            FROM
              public.completed_evaluations,
              public.eval_session_activities,
              public.evaluation_sessions,
              public.evaluation_session_cohorts
            WHERE
              completed_evaluations.eval_session_activity_id = eval_session_activities.id AND
              eval_session_activities.evaluation_session_id = evaluation_sessions.id AND
              evaluation_session_cohorts.id = eval_session_activities.evaluation_session_cohort_id AND
               (evaluation_sessions.id = #{id.to_s})
            group by evaluation_session_cohorts.name;"
      records_array = ActiveRecord::Base.connection.execute(sql).values


      records_array.each do |record|
        downloadable << id.to_s + ',' + record[1] + ',' + record[0].to_s
      end
    end
    downloadable = downloadable.join("\n")

    send_data downloadable, :type => 'text/csv; charset=iso-8859-1; header=present', filename: "raport_grupe.csv"


  end

  def download_all()

    #ids=[16,17,20,21,26,27,30,31]
    #ids = [36,38,39,42,35,37,40,41]

    #   ids = [43,44,45,46,47,48,49,50]
    ids = [54, 57, 59, 55, 56, 58]
    # ids = EvaluationSession.all.pluck(:id)
    sql = "SELECT evaluation_sessions.id as id, evaluation_sessions.semester as semestru ,
             concat( concat( teachers.last_name, ' ') ,  teachers.first_name) as nume, courses.title as materie,
             eval_session_activities.activity_type as tip, completed_evaluations.content as continut
            FROM
              public.courses,
              public.teachers,
              public.eval_session_activities,
              public.evaluation_sessions,
              public.completed_evaluations
            WHERE
              eval_session_activities.course_id = courses.id AND
              eval_session_activities.teacher_id = teachers.id AND
              eval_session_activities.evaluation_session_id = evaluation_sessions.id AND
              eval_session_activities.id = completed_evaluations.eval_session_activity_id and
              (evaluation_sessions.id in (#{ids.join(', ')}))
            Order by evaluation_sessions.id, evaluation_sessions.semester , teachers.last_name, teachers.first_name,courses.title, eval_session_activities.activity_type ;"
    records_array = ActiveRecord::Base.connection.execute(sql).values

    downloadable = []
    downloadable << ['id', 'semestru', 'nume', 'materie', 'tip', 'continut'].join(',')
    records_array.each do |record|
      record[5] = record[5].gsub(',', ';')
      downloadable << record.join(',')
    end
    downloadable = downloadable.join("\n")


    send_data downloadable, :type => 'text/csv; charset=iso-8859-1; header=present', filename: "raport.csv"

  end

  def download_all_pdf
    #ids = [54, 57, 59, 55, 56, 58]
    #ids = [1, 2]
    ids = []
    ids = unless params[:id].nil? || params[:id].empty?
            [params[:id]]
          end

    root = DOCUMENTS_PATH
    pathi = File.join(root, 'evaluari')
    if Dir.exist?(root)
      FileUtils.rm_rf([root])
    end
    system 'mkdir', '-p', root.to_s

    system 'mkdir', '-p', pathi.to_s

    teachers = Teacher.all

    evaluation_sessions = EvaluationSession.where(id: ids)

    evaluation_sessions.each do |current_session|
      teachers.each do |teacher|

        Course.all.each do |course|

          TYPES.each do |type|
            eval_session_activities = EvalSessionActivity.where(
                teacher_id: teacher.id,
                evaluation_session_id: current_session.id,
                course_id: course.id,
                activity_type: type)
            if eval_session_activities && eval_session_activities.size > 0
              begin
                pdf1 = PdfComments.new(course.id, teacher.id, type, current_session)
                path1 = File.join(pathi, "#{teacher.last_name} #{teacher.first_name} #{course.title}-#{type} - comentarii.pdf".force_encoding('UTF-8'))
                pdf1.render_file(path1)
              rescue => e
                print e
              end
              begin
                path2 = File.join(pathi, "#{teacher.last_name} #{teacher.first_name} #{course.title}-#{type} - grila.pdf".force_encoding('UTF-8'))
                pdf2 = generate_evaluation_questions(course, teacher, type, current_session, eval_session_activities)

                pdf2.to_file(path2)
              rescue => e
                print e
              end
            end
          end
        end
      end
    end

    zipfile_name = File.join(root, 'evaluari.zip')
    Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
      Dir.children(pathi).each do |filename|

        zipfile.add(filename, File.join(pathi, filename))
      end

    end
    send_file(zipfile_name, :type => 'application/zip', :filename => 'evaluari.zip')
  end

end

app/helpers/statistics_helper.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

module StatisticsHelper
  include EvaluationSessionsHelper

  def get_activities_for_session_and_course(session_id, course_id)

    return EvalSessionActivity.select { |activity| activity.evaluation_session_id == session_id and activity.course_id == course_id }.group_by { |s| [s.teacher_id, s.activity_type] }
  end

  def get_activities_for_session_and_teacher(session_id, teacher_id)

    return EvalSessionActivity.select { |activity| activity.evaluation_session_id == session_id and activity.teacher_id == teacher_id }.group_by { |s| [s.course_id, s.activity_type] }

  end
  
  def generate_evaluation_questions(course, teacher, type, active_session, ev)
    model = {}
    model['course'] = course
    model['teacher'] = teacher
    model['activityType'] = type
    model['session_activities'] = ev

    model['participants_no'] = CompletedEvaluation.where(eval_session_activity: model['session_activities']).size

    model['completed_for_activity'] = CompletedEvaluation.where(eval_session_activity: model['session_activities']).pluck(:content)
    model['activity_results'] = []
    model['completed_for_activity'].each do |content|
      model['activity_results'] << JSON.parse(content)
    end
    form = if model['activityType'] == 'Curs'
      active_session.form
    else
      if model['activityType'] == 'Seminar'
        active_session.formS
      else
        if model['activityType'] == 'Laborator'
          active_session.formL
        else
          active_session.formP
               end
             end
           end

    require 'json'
    form_content = JSON.parse form.content
    model['content'] = form_content["chestionar"]
    model['departments_select'] = Department.all

    votes = []
    nr = 0
    model['content'].each do |section|
      section.each do |parent|
        if parent["intrebare"]
          r = if parent["intrebare"].first["enunt"]
            parent["intrebare"].drop 1
          else
            parent["intrebare"]
              end
          votes[nr+1] = get_votes(model['activity_results'], nr+1, r.count)
          nr = nr + 1
        end
      end

    end
    model['votes'] = votes

    @mod = model

    pdf = PDFKit.new(
        (render_to_string template: 'templates/completed_eval.pdf.erb',
                          layout: false))
    pdf


  end
end

app/views/statistics/course_statistics.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<div class="page-header">

  <h1>
    Evaluarile materiei <b> <%= @course.title %></b>
  </h1>
  <%= link_to view_statistics_path, class: 'btn' do %>
      <i class="glyphicon glyphicon-chevron-left glyphicon glyphicon-"></i>
      Inapoi la pagina de statistici
  <% end %>
</div>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <% @evaluation_sessions.each do |evaluation_session| %>
        <div class="panel-heading" role="tab" id="heading-<%= evaluation_session.id %>>">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse-<%= evaluation_session.id %>" aria-expanded="false" aria-controls="collapse-<%= evaluation_session.id %>" class="collapsed">
              Perioada: <%= evaluation_session.start_date.strftime('%d/%m/%y') %>
              - <%= evaluation_session.end_date.strftime('%d/%m/%y') %>
              <br>
              Semestrul <%= evaluation_session.semester %>/<%= evaluation_session.year %>
              -<%= evaluation_session.year + 1 %>
            </a>
          </h4>
        </div>

        <div id="collapse-<%= evaluation_session.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<%= evaluation_session.id %>">
          <div class="panel-body">
            <% if !evaluation_session.form.nil? %>
                <h4>
                  Chestionar Curs
                  <b><%= link_to evaluation_session.form.title, evaluation_session.form, remote: true %></b>
                </h4>
            <% end %>
            <% if !evaluation_session.formS.nil? %>
                <h4>
                  Chestionar Seminar
                  <b><%= link_to evaluation_session.formS.title, evaluation_session.formS, remote: true %></b>
                </h4>
            <% end %>
            <% if !evaluation_session.formL.nil? %>
                <h4>
                  Chestionar Laborator
                  <b><%= link_to evaluation_session.formL.title, evaluation_session.formL, remote: true %></b>
                </h4>
            <% end %>
            <% if !evaluation_session.formP.nil? %>
            <h4>
              Chestionar Proiect:
              <b><%= link_to evaluation_session.formP.title, evaluation_session.formP, remote: true %></b>
            </h4>
            <% end %>
            <div class="table-responsive">
              <table class="table table-striped  table-hover">
                <thead>
                <tr>
                  <th>Profesor</th>
                  <th>Tip Activitate</th>
                  <th></th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                <% activities = get_activities_for_session_and_course(evaluation_session.id, @course.id) %>
                <% activities.each do |key, activities| %>
                    <tr>
                      <td>
                        <% teacher = Teacher.find_by_id(key[0]) %>
                        <%= teacher.last_name %> <%= teacher.first_name %>
                      </td>
                      <td><%= key[1] %></td>
                      <td><%= link_to 'Vezi Evaluare', view_evaluation_path(:courseId => @course.id, :teacherId => key[0], :type => key[1], :active_session => evaluation_session), remote: true, class: 'btn btn-info' %></td>
                      <td><%= link_to 'Descarca Comentarii', get_comments_path(:courseId => @course.id, :teacherId => key[0], :type => key[1], :active_session => evaluation_session), class: 'btn btn-info' ,  download:true %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>

          </div>
        </div>

    <% end %>
  </div>
</div>

app/views/statistics/index.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<div class="page-header">
  <h1>Statistici</h1>
  <hr/>
  <%= link_to 'Descarca tot csv!', {:controller => "statistics", :action => "download_all" }, method: :get, class: 'btn btn-info' %>
<hr/>
  <%= link_to 'Descarca Raport pe grupe!', {:controller => "statistics", :action => "download_by_cohorts" }, method: :get, class: 'btn btn-info' %>
<!--<hr/>-->
  <%#= link_to 'Descarca arhiva cu pdf!', {:controller => "statistics", :action => "download_all_pdf" }, method: :get, class: 'btn btn-info' %>
</div>


<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#course" aria-controls="course" role="tab" data-toggle="tab">Materii</a>
    </li>
    <li role="presentation">
      <a href="#teacher" aria-controls="teacher" role="tab" data-toggle="tab">Profesori</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="course">

      <div class="table-responsive">

        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th>Denumire</th>
            <th></th>
          </tr>
          </thead>
          <tbody>

          <% @courses.each do |course| %>
              <tr>
                <td>
                  <%= course.title %>
                </td>
                <td>
                  <a href="course_statistics/<%= course.id %>">vezi evaluari</a>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="teacher">
      <div class="table-responsive">

        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th>Nume</th>
            <th>Prenume</th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <% @teachers.each do |teacher| %>
              <tr>

                <td><%= teacher.last_name %></td>
                <td><%= teacher.first_name %></td>
                <td>
                  <a href="teacher_statistics/<%= teacher.id %>">vezi evaluari</a>
                </td>

              </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>
<br>

app/views/statistics/teacher_statistics.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<div class="page-header">

  <h1>
    Evaluarile profesorului <b> <%= @teacher.first_name %> <%= @teacher.last_name %></b>
  </h1>
  <%= link_to view_statistics_path, class: 'btn' do %>
      <i class="glyphicon glyphicon-chevron-left glyphicon glyphicon-"></i>
      Inapoi la pagina de statistici
  <% end %>
</div>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <% @evaluation_sessions.each do |evaluation_session| %>
        <div class="panel-heading" role="tab" id="heading-<%= evaluation_session.id %>>">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse-<%= evaluation_session.id %>" aria-expanded="false" aria-controls="collapse-<%= evaluation_session.id %>" class="collapsed">
              Perioada: <%= evaluation_session.start_date.strftime('%d/%m/%y') %>
              - <%= evaluation_session.end_date.strftime('%d/%m/%y') %>
              <br>
              Semestrul <%= evaluation_session.semester %>/<%= evaluation_session.year %>
              -<%= evaluation_session.year + 1 %>
            </a>
          </h4>
        </div>

        <div id="collapse-<%= evaluation_session.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<%= evaluation_session.id %>">
          <div class="panel-body">
            <% if !evaluation_session.form.nil? %>
                <h4>
                  Chestionar Curs
                  <b><%= link_to evaluation_session.form.title, evaluation_session.form, remote: true %></b>
                </h4>
            <% end %>
            <% if !evaluation_session.formS.nil? %>
                <h4>
                  Chestionar Seminar
                  <b><%= link_to evaluation_session.formS.title, evaluation_session.formS, remote: true %></b>
                </h4>
            <% end %>
            <% if !evaluation_session.formL.nil? %>
                <h4>
                  Chestionar Laborator
                  <b><%= link_to evaluation_session.formL.title, evaluation_session.formL, remote: true %></b>
                </h4>
            <% end %>
            <% if !evaluation_session.formP.nil? %>
                <h4>
                  Chestionar Proiect:
                  <b><%= link_to evaluation_session.formP.title, evaluation_session.formP, remote: true %></b>
                </h4>
            <% end %>
            <div class="table-responsive">
              <table class="table table-striped table-hover">
                <thead>
                <tr>
                  <th>Materie</th>
                  <th>Tip Activitate</th>
                  <th></th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                <% activities = get_activities_for_session_and_teacher(evaluation_session.id, @teacher.id) %>
                <% activities.each do |key, activities| %>
                    <tr>
                      <td>
                        <% course = Course.find_by_id(key[0]) %>
                        <%= course.title %>
                      </td>
                      <td><%= key[1] %></td>
                      <td><%= link_to 'Vezi Evaluare', view_evaluation_path(:courseId => key[0], :teacherId => @teacher.id, :type => key[1], :active_session => evaluation_session), remote: true, class: 'btn btn-info' %></td>
                      <td><%= link_to 'Descarca Comentarii', get_comments_path(:courseId => key[0], :teacherId => @teacher.id, :type => key[1], :active_session => evaluation_session), class: 'btn btn-info' ,  download:true %></td>
                      <td><%= link_to 'Descarca Intrebari Grila', download_evaluation_path(:courseId => key[0], :teacherId => @teacher.id, :type => key[1], :active_session => evaluation_session), class: 'btn btn-info',  download:true  %>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>

          </div>
        </div>

    <% end %>
  </div>
</div>