config/routes.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Rails.application.routes.draw do


  resources :teachers do
    get 'delete'
    match 'import', :via => [:get, :post], :as => 'import'
    get 'download'
    get 'import_from_app'
  end
  resources :departments do
    get 'delete'
  end
  resources :forms do
    get 'delete'
  end
  resources :courses do
    get 'delete'
    match 'reset', :via => [:get, :post], :as => 'reset'
    match 'import', :via => [:get, :post], :as => 'import'
    get 'download'

  end
  resources :activities do
    get 'delete'
    get 'editS'
    get 'deleteS'
    get 'destroyS'
    get 'newS'
    match 'updateS', :via => [:patch, :post]
    get 'deleteall'
  end

  resources :cohorts do
    get 'delete'
    match 'import', :via => [:get, :post], :as => 'import'
    get 'import_from_app'
    get 'download'
  end
  resources :evaluation_sessions do
    get 'delete'
    match 'activate', :via => [:get, :post], :as => 'activate_session'
    match 'finalize', :via => [:get, :post], :as => 'finalize_session'
    match 'generate', :via => [:get, :post], :as => 'generate'
    get 'get_tokens'
  end

  get 'get_comments', :to => 'evaluation_sessions#get_comments'
  get 'get_comments_p', :to => 'prof#get_comments'
  match 'view_evaluation', :via => [:get, :post], :to => 'evaluation_sessions#view_evaluation'
  get 'descarca', :to => 'evaluation_sessions#descarca', :format => 'pdf'
  get 'download_evaluation', :to => 'evaluation_sessions#download_evaluation', :format => 'pdf'
  get 'download_evaluation_p', :to => 'prof#download_evaluation', :format => 'pdf'

  get 'evaluate' => 'evaluation#index'
  match 'evaluate_activity', :via => [:post, :get], :to => 'evaluation#evaluate_activity'
  match 'view_evaluation', :via => [:post, :get], :to => 'evaluation#view_evaluation'
  match 'view_eval_p', :via => [:post, :get], :to => 'prof#view_evaluation'

  match 'course_list', :via => [:post, :get], :to => 'courses#course_list'
  match 'cohort_list', :via => [:post, :get], :to => 'cohorts#cohort_list'
  match 'activities_neterminal_list', :via => [:post, :get], :to => 'evaluation_sessions#activities_neterminal_list'
  match 'activities_terminal_list', :via => [:post, :get], :to => 'evaluation_sessions#activities_terminal_list'

  get 'home/index'

  match 'set_visibility' , :via => [:post, :get], :to => 'evaluation_sessions#set_visibility'


  post 'create_active_user' => 'home#create'

  get 'view_statistics' => 'statistics#index'
  get 'download_all', :to => 'statistics#download_all'
  match 'download_all_pdf/:id', :to => 'statistics#download_all_pdf', via: :get, as: 'download_all_pdf'
  get 'download_by_cohorts', :to => 'statistics#download_by_cohorts'

  get 'course_statistics/:course_id' => 'statistics#course_statistics'
  get 'teacher_statistics/:teacher_id' => 'statistics#teacher_statistics'

  get 'evaluation_form/:activity_id' => 'evaluation#eval_form'

  get 'form_archive' =>'form#list_all'



  get 'control_panel' => 'control_panel#index'
  get 'control_panel/:tab' => 'control_panel#index'


  #get 'admin' => 'admin#index'

  get 'admin' => 'evaluation_sessions#current_session'

  get 'prof/index'

  get 'new_session' => 'evaluation_sessions#new1'
  get 'evaluation_sessions' => 'evaluation_sessions#index'

  get 'delete_all_activities_for_exam' => 'activities#delete_all_activities_for_exam'

  root 'home#index'

  match '/token_sign_out', to: 'home#abort_token_session', as: 'token_sign_out', via: [:get, :post]

  # omniauth
  match '/auth/:provider/callback', :via => [:get, :post], :to => 'user_sessions#create'
  match '/auth/failure', :via => [:get, :post], :to => 'user_sessions#failure'

  # Custom logout
  # match '/logout', :via => [:get, :post], :to => 'user_sessions#destroy'
  get 'alogin', to: 'user_sessions#new', as: 'login'
  get 'logout', to: 'user_sessions#destroy', as: 'logout'
  post 'alogin', to: 'user_sessions#create'

  #match 'test', :via => [:get], :to => 'cohorts#getAllCohorts'

end

app/models/teacher.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

class Teacher < ActiveRecord::Base
  has_many :activities, dependent: :destroy
  has_many :eval_session_activities, dependent: :destroy

  def self.as_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/teachers_controller.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

class TeachersController < AdminController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  respond_to :html, :js


  def index
    get_all_teachers
  end


  def show
  end


  def new
    @teacher = Teacher.new
  end


  def edit
  end


  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.save
    get_all_teachers
    respond_to do |format|
      format.js
    end
  end


  def update
    @teacher.update(teacher_params)
    get_all_teachers
  end


  def destroy
    @teacher.destroy
    get_all_teachers
  end

  def delete
    @teacher = Teacher.find(params[:teacher_id])
  end


  require 'csv'

  def import
    @errors =[]
    if request.post?
      CSV.parse params[:csv] do |row|
        Teacher.create(first_name: row[1].to_s.squish, last_name: row[0].to_s.squish,email: row[2].to_s.squish)
      end
      get_all_teachers
    end


    respond_to do |format|
      format.js
    end
  end

  def download
    teachers = Teacher.all

    send_data teachers.as_csv, filename: "Profesori.csv", type: 'application/csv', disposition: 'attachment'
  end

  require 'net/http'
  require 'rest_client'
  require 'json'

  def import_from_app
    @errors =[]

    str = "#{API_URL}teachers?oauth_token=#{@current_user.token}"
    info = JSON.parse RestClient.get str, {:accept => :json}

    if not info['error'].nil?
      redirect_to logout_path
      return
    end

    print info['data'].inspect

    info['data'].each do |ch|
      department_name = ch['department'] == 'TCI' ? 'CTI' : ch['department']

      department = Department.find_by_name department_name

      teacher = Teacher.find_by_first_name_and_last_name ch['first_name'], ch['last_name']
      if teacher.nil?
        teacher = Teacher.new
      end

      teacher.first_name = ch['first_name']
      teacher.last_name = ch['last_name']
      teacher.email = ch['email']
      teacher.department = department

      teacher.save
    end
    get_all_teachers

    respond_to do |format|
      format.js
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  def get_all_teachers
    @teachers = Teacher.order(:last_name)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :email)
  end
end

app/helpers/teachers_helper.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

module TeachersHelper
end

app/views/teachers/_delete.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<div class="modal-body">
  <ul class="errors"></ul>

  Sigur doriti sa stergeti profesorul <b><%= @teacher.first_name + ' ' + @teacher.last_name %></b>?
  <br>
  Aceasta actiune este ireversibila!
</div>
<div class="modal-footer">
  <%= link_to 'DA', teacher_path(@teacher), method: :delete, remote: true, class: "btn btn-danger" %>
  <%= link_to 'NU', '', class: "btn btn-default", data: {dismiss: "modal"} %>
</div>

app/views/teachers/_edit.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<div class="modal-header">

  <%= link_to '&times;'.html_safe, '', class: 'close', data: {dismiss: "modal"} %>
  <h3> Editeaza Profesor </h3>
</div>
<%= render 'form' %>

app/views/teachers/_form.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<%= form_for @teacher, remote: true, html: {class: "form-horizontal", style: "display:inline;"} do |f| %>
    <div class="modal-body">
      <div class="panel-body">
        <div class=" has-error errors">
        </div>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <label class="col-lg-5 control-label text-primary" for="start_period">Nume:</label>

          <div class="col-lg-7">
            <%= f.text_field :last_name, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-5 control-label text-primary" for="start_period">Prenume:</label>

          <div class="col-lg-7">
            <%= f.text_field :first_name, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-lg-5 control-label text-primary" for="start_period">Email:</label>

          <div class="col-lg-7">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= f.submit 'Salveaza', class: "btn btn-primary" %>
      <%= link_to "Cancel", '', class: "btn btn-default", data: {dismiss: "modal"} %>
    </div>
<% end %>

app/views/teachers/_import.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<div class="modal-header">

  <%= link_to '&times;'.html_safe, '', class: 'close', data: {dismiss: "modal"} %>
  <h3> Importa Profesori </h3>
</div>
<%= form_tag teacher_import_path(0), method: :post, remote: true, html: {class: "form-horizontal", style: "display:inline;"} do %>
    <div class="modal-body">
      <div class="panel-body">
        <div class=" has-error errors">
        </div>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <div class="alert alert-info"> Pentru a adauga mai multi profesori scrie mai jos continutul unui CSV (de forma
            Nume, Prenume, Email)
          </div>
        </div>
        <div class="form-group">
          <%= text_area_tag :csv, '', class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= submit_tag 'Salveaza', class: "btn btn-primary" %>
      <%= link_to "Cancel", '', class: "btn btn-default", data: {dismiss: "modal"} %>
    </div>
<% end %>

app/views/teachers/_import_success.js.erb
/*
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

$("div.errors").html("")
<% if @errors.any? %>
<% @errors.full_messages.each do |message| %>
$("div.errors").append($("<div class='control-label' />").html("<%= message.html_safe %>"))
<% end %>

<% else %>
$(".teachers-index").html("<%= escape_javascript(render 'teachers/index') %>")
$("#session-modal").modal("hide")

<% end %>

app/views/teachers/_index.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<div class="well">
  <%= link_to new_teacher_path, remote: true, class: 'btn btn-primary btn-no-padding' do %>
        <span class="btn-label">
			<span class="fa  fa-plus"></span>
        </span>
      Adauga
  <% end %>
 <!-- <%#= link_to teacher_import_from_app_path(0), action: :get, remote: true, class: 'btn btn-primary btn-no-padding' do %>
        <span class="btn-label">
			<span class="fa fa-upload"></span>
        </span>
      Importa de la autentificare
  <%# end %>-->
  <%= link_to teacher_import_path(0), action: :get, remote: true, class: 'btn btn-primary btn-no-padding' do %>
        <span class="btn-label">
			<span class="fa fa-upload"></span>
        </span>
      Importa
  <% end %>
  <%= link_to teacher_download_path(0), action: :get, class: 'btn btn-primary btn-no-padding',  download:true  do %>
        <span class="btn-label">
			<span class="fa fa-download"></span>
        </span>
      Descarca (CSV)
  <% end %>
</div>

<!--<div class="table-responsive"> -->
  <div id="main" role="main" class="block">

  <table id="example"  class="table table-striped table-hover" cellspacing="0" width="100%">
    <thead>
    <tr>
      <th>Nume</th>
      <th>Prenume</th>
      <th>Email</th>
      <th></th>
    </tr>
    </thead>
    <tbody class="session-index">

    <% @teachers.each do |teacher| %>
        <tr>
          <td>
            <%= teacher.last_name %>
          </td>
          <td>
            <%= teacher.first_name %>
          </td>
          <td>
            <%= teacher.email %>
          </td>
          <td>
            <%= link_to '', edit_teacher_path(teacher), remote: true, class: 'btn glyphicon glyphicon-edit' %>
            <%= link_to '', teacher_delete_path(teacher.id), remote: true, class: 'btn glyphicon glyphicon-trash' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>

<script>
    $(document).ready(function() {

        $('#example').DataTable();
    } );
</script>

app/views/teachers/_save.js.erb
/*
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

$("div.errors").html("")
<% if @teacher.errors.any? %>
<% @teacher.errors.full_messages.each do |message| %>
$("div.errors").append($("<div class='control-label' />").html("<%= message.html_safe %>"))
<% end %>

<% else %>
$(".teachers-index").html("<%= escape_javascript(render 'teachers/index') %>")
$("#session-modal").modal("hide")
$("#session-modal-small").modal("hide")
<% end %>

app/views/teachers/index.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<table>
  <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.email %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>