config/routes.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Rails.application.routes.draw do


  resources :teachers do
    get 'delete'
    match 'import', :via => [:get, :post], :as => 'import'
    get 'download'
    get 'import_from_app'
  end
  resources :departments do
    get 'delete'
  end
  resources :forms do
    get 'delete'
  end
  resources :courses do
    get 'delete'
    match 'reset', :via => [:get, :post], :as => 'reset'
    match 'import', :via => [:get, :post], :as => 'import'
    get 'download'

  end
  resources :activities do
    get 'delete'
    get 'editS'
    get 'deleteS'
    get 'destroyS'
    get 'newS'
    match 'updateS', :via => [:patch, :post]
    get 'deleteall'
  end

  resources :cohorts do
    get 'delete'
    match 'import', :via => [:get, :post], :as => 'import'
    get 'import_from_app'
    get 'download'
  end
  resources :evaluation_sessions do
    get 'delete'
    match 'activate', :via => [:get, :post], :as => 'activate_session'
    match 'finalize', :via => [:get, :post], :as => 'finalize_session'
    match 'generate', :via => [:get, :post], :as => 'generate'
    get 'get_tokens'
  end

  get 'get_comments', :to => 'evaluation_sessions#get_comments'
  get 'get_comments_p', :to => 'prof#get_comments'
  match 'view_evaluation', :via => [:get, :post], :to => 'evaluation_sessions#view_evaluation'
  get 'descarca', :to => 'evaluation_sessions#descarca', :format => 'pdf'
  get 'download_evaluation', :to => 'evaluation_sessions#download_evaluation', :format => 'pdf'
  get 'download_evaluation_p', :to => 'prof#download_evaluation', :format => 'pdf'

  get 'evaluate' => 'evaluation#index'
  match 'evaluate_activity', :via => [:post, :get], :to => 'evaluation#evaluate_activity'
  match 'view_evaluation', :via => [:post, :get], :to => 'evaluation#view_evaluation'
  match 'view_eval_p', :via => [:post, :get], :to => 'prof#view_evaluation'

  match 'course_list', :via => [:post, :get], :to => 'courses#course_list'
  match 'cohort_list', :via => [:post, :get], :to => 'cohorts#cohort_list'
  match 'activities_neterminal_list', :via => [:post, :get], :to => 'evaluation_sessions#activities_neterminal_list'
  match 'activities_terminal_list', :via => [:post, :get], :to => 'evaluation_sessions#activities_terminal_list'

  get 'home/index'

  match 'set_visibility' , :via => [:post, :get], :to => 'evaluation_sessions#set_visibility'


  post 'create_active_user' => 'home#create'

  get 'view_statistics' => 'statistics#index'
  get 'download_all', :to => 'statistics#download_all'
  match 'download_all_pdf/:id', :to => 'statistics#download_all_pdf', via: :get, as: 'download_all_pdf'
  get 'download_by_cohorts', :to => 'statistics#download_by_cohorts'

  get 'course_statistics/:course_id' => 'statistics#course_statistics'
  get 'teacher_statistics/:teacher_id' => 'statistics#teacher_statistics'

  get 'evaluation_form/:activity_id' => 'evaluation#eval_form'

  get 'form_archive' =>'form#list_all'



  get 'control_panel' => 'control_panel#index'
  get 'control_panel/:tab' => 'control_panel#index'


  #get 'admin' => 'admin#index'

  get 'admin' => 'evaluation_sessions#current_session'

  get 'prof/index'

  get 'new_session' => 'evaluation_sessions#new1'
  get 'evaluation_sessions' => 'evaluation_sessions#index'

  get 'delete_all_activities_for_exam' => 'activities#delete_all_activities_for_exam'

  root 'home#index'

  match '/token_sign_out', to: 'home#abort_token_session', as: 'token_sign_out', via: [:get, :post]

  # omniauth
  match '/auth/:provider/callback', :via => [:get, :post], :to => 'user_sessions#create'
  match '/auth/failure', :via => [:get, :post], :to => 'user_sessions#failure'

  # Custom logout
  # match '/logout', :via => [:get, :post], :to => 'user_sessions#destroy'
  get 'alogin', to: 'user_sessions#new', as: 'login'
  get 'logout', to: 'user_sessions#destroy', as: 'logout'
  post 'alogin', to: 'user_sessions#create'

  #match 'test', :via => [:get], :to => 'cohorts#getAllCohorts'

end

app/controllers/courses_controller.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

class CoursesController < AdminController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  respond_to :html, :js

  include CoursesHelper

  def index
    get_courses
  end

  def course_list
    if params['department'] != ''
      @courses = Course.order(:title).where(department_id: params['department'])
    else
      @courses = Course.order(:title)
    end
    respond_to do |format|
      format.js
    end
  end


  def edit
  end

  def update
    @course.update(course_params)
    get_courses
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    @course.save
    get_courses
    respond_to do |format|
      format.js
    end
  end

  def delete
    @course = Course.find(params[:course_id])
  end

  def destroy
    @course.destroy
    get_courses
  end

  require 'csv'

  def import
    @errors =[]
    if request.post?
      CSV.parse params[:csv] do |row|
        dep = Department.find_by_name(row[2].to_s.squish)
        if !dep.nil?
          Course.create(title: row[0].to_s.squish, uid: row[1].to_s.squish, department_id: dep.id)
        end

      end
      get_courses
    end
    respond_to do |format|
      format.js
    end
  end

  def download
    courses = []

    Course.pluck(:title,  :department_id).each do |course|
      course << Department.find_by_id(course[1]).name
      courses << course
    end
    send_data course_as_csv(courses), filename: "Materii.csv", type: 'application/csv', disposition: 'attachment'
  end

=begin

  def reset

    if request.post?
      # str = "#{CUSTOM_PROVIDER_URL}/students/#{@current_user.uid}?oauth_token=#{@current_user.token}"
      str = "http://193.226.51.18/students/#{@current_user.uid}?oauth_token=#{@current_user.token}"


      #:8091
       @info = JSON.parse(open(str).read)

       print @info
    end

    @courses = Course.all

  end
=end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  def get_courses
    @courses = Course.order(:title)
    @departments_select = Department.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def course_params
    params.require(:course).permit(:title, :department_id)
  end
end

app/helpers/courses_helper.rb
# Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

module CoursesHelper

  def course_as_csv(all)
    CSV.generate do |csv|
      csv << ['title',  'deparment_id', 'department_name']
      all.each do |item|
        #csv << "#{item.title},#{item.uid},#{item.department_id}"
        csv << item
      end
    end
  end
end

app/views/courses/_delete.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<div class="modal-body">
  <ul class="errors"></ul>

  Sigur doriti sa stergeti materia <b><%= @course.title %></b>?
  <br>
  Aceasta actiune este ireversibila!
</div>
<div class="modal-footer">
  <%= link_to 'DA', course_path(@course), method: :delete, remote: true, class: "btn btn-danger" %>
  <%= link_to 'NU', '', class: "btn btn-default", data: {dismiss: "modal"} %>
</div>

app/views/courses/_edit.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<div class="modal-header">

  <%= link_to '&times;'.html_safe, '', class: 'close', data: {dismiss: "modal"} %>
  <h3> Editeaza Materie </h3>
</div>
<%= render 'form' %>

app/views/courses/_form.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<%= form_for @course, remote: true, html: {class: "form-horizontal", style: "display:inline;"} do |f| %>
    <div class="modal-body">
      <div class="panel-body">
        <div class=" has-error errors">
        </div>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <label class="col-lg-5 control-label text-primary" for="start_period">Denumire:</label>

          <div class="col-lg-7">
            <%= f.text_field :title, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-5 control-label text-primary">Departament:</label>

          <div class="col-lg-7">
            <%= f.select :department_id, Department.all.collect { |p| [p.name, p.id] }, {selected: @course.department_id, include_blank: true}, class: 'form-control  col-xs-9' %>
          </div>
        </div>
       <!-- <div class="form-group">
          <div class="alert alert-info">Codul unic de identificare este format din numarul domeniului, numarul
            programului de studiu, an, semestru si numarul disciplinei din planul de invatamant.
          </div>
        </div>
        <div class="form-group">
          <label class="col-lg-5 control-label text-primary" for="start_period">Cod unic de identificare al
            materiei:</label>

          <div class="col-lg-7">
            <%= f.text_field :uid, class: 'form-control' %>
          </div>
        </div>-->
      </div>
    </div>
    <div class="modal-footer">
      <%= f.submit class: "btn btn-primary" %>
      <%= link_to "Cancel", '', class: "btn btn-default", data: {dismiss: "modal"} %>
    </div>
<% end %>

app/views/courses/_import.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<div class="modal-header">

  <%= link_to '&times;'.html_safe, '', class: 'close', data: {dismiss: "modal"} %>
  <h3> Importa Materii </h3>
</div>
<%= form_tag course_import_path(0), method: :post, remote: true, html: {class: "form-horizontal", style: "display:inline;"} do %>
    <div class="modal-body">
      <div class="panel-body">
        <div class=" has-error errors">
        </div>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <div class="alert alert-info"> Pentru a adauga mai multe materii scrie mai jos continutul unui CSV (de forma
            Titlu, Cod de identificare, Departament)
          </div>
        </div>
        <div class="form-group">
          <%= text_area_tag :csv, '', class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= submit_tag 'Salveaza', class: "btn btn-primary" %>
      <%= link_to "Cancel", '', class: "btn btn-default", data: {dismiss: "modal"} %>
    </div>
<% end %>

app/views/courses/_import_success.js.erb
/*
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

$("div.errors").html("")
<% if @errors.any? %>
<% @errors.full_messages.each do |message| %>
$("div.errors").append($("<div class='control-label' />").html("<%= message.html_safe %>"))
<% end %>

<% else %>
$(".courses-index").html("<%= escape_javascript(render 'courses/index') %>")
$("#session-modal").modal("hide")

<% end %>

app/views/courses/_index.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<div class="well">
  <div class="col-md-4">

    <%= form_tag course_list_path, remote: true, class: "form-horizontal form", style: "display:inline;" do %>
        <%= select_tag :department, options_from_collection_for_select(@departments_select, 'id', 'name', '0'), include_blank: 'Toate', class: 'form-control ', :onChange => 'your_onchange_handler()' %>
    <% end %>
  </div>


  <%= link_to new_course_path, remote: true, class: 'btn btn-primary btn-no-padding' do %>
  <span class="btn-label">
			<span class="fa  fa-plus"></span>
        </span>
      Adauga
  <% end %>
  <!-- <%= link_to 'Actualizeaza materiile ', course_reset_path(0), remote: true, class: 'btn btn-default' %>-->
  <%= link_to course_import_path(0), action: :get, remote: true, class: 'btn btn-primary btn-no-padding' do %>
        <span class="btn-label">
			<span class="fa fa-upload"></span>
        </span>
      Importa
  <% end %>
  <%= link_to course_download_path(0), action: :get, class: 'btn btn-primary btn-no-padding',  download:true  do %>
        <span class="btn-label">
			<span class="fa fa-download"></span>
        </span>
      Descarca (CSV)
  <% end %>
</div>


<div class="table-responsive">

  <table id='coursesTab' class="table table-striped table-hover"cellspacing="0" width="100%">
    <thead>
    <tr>
      <th>Denumire</th>
      <th>Departament</th>
      <th></th>
    </tr>
    </thead>
    <tbody class="course-list">
    <% @courses.each do |course| %>
        <tr>
          <td>
            <%= course.title %>
          </td>
          <td>
            <% if !course.department.nil? %>
                  <%= course.department.name %>

             <% end %>
          </td>
          <td>
            <%= link_to '', edit_course_path(course), remote: true, class: 'btn glyphicon glyphicon-edit' %>
            <%= link_to '', course_delete_path(course.id), remote: true, class: 'btn glyphicon glyphicon-trash' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br>

<script type="application/javascript">



        $(document).ready(function() {

            $('#coursesTab').DataTable();
        } );
</script>

app/views/courses/_new.html.erb
<!--
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
-->

<div class="modal-header">

  <%= link_to '&times;'.html_safe, '', class: 'close', data: {dismiss: "modal"} %>
  <h3> Adauga Materie </h3>
</div>
<%= render 'form' %>

app/views/courses/_save.js.erb
/*
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

$("div.errors").html("")
<% if @course.errors.any? %>
<% @course.errors.full_messages.each do |message| %>
$("div.errors").append($("<div class='control-label' />").html("<%= message.html_safe %>"))
<% end %>

<% else %>
$(".courses-index").html("<%= escape_javascript(render 'courses/index') %>")
$("#session-modal").modal("hide")
$("#session-modal-small").modal("hide")
<% end %>

app/views/courses/course_list.js.erb
/*
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

$(".course-list").html("<%= escape_javascript(render  'courses/course_list') %>")

app/views/courses/delete.js.erb
/*
Copyright (c) 2015 - 2020 Ana-Cristina Turlea <turleaana@gmail.com>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

$("#inner-session-modal-sm").html("<%= escape_javascript(render 'delete') %>")
$("#session-modal-small").modal("show")